### ISSUE TITLE
Pretraining weight on Ref-COCO

### ISSUE THREAD

**Issue by itruonghai** [lxa9867/R2VOS#2]
Could you release the pretraining weight?

**Comment by lxa9867** [comment]
Do you mean the coco pretraining code?

**Comment by itruonghai** [comment]
code and weight also, I need weight to fine-tune on Ref-Youtube-VOS?

**Comment by lxa9867** [comment]
I am sorry that I cannot provide either the code or weight due to the company policy. Actually, this repo is not the official repo as the company doesn't permit me to release the code. 

If you want to have the pre-trained weight and also fine-tune on Ref-YTVOS. You can use the training scripts at [ReferFormer](https://github.com/wjn922/ReferFormer). Our scripts are basically the same.
